"""Provenance stamps for exported artifacts (figures, tracks, data files).

Lets a reviewer trace any exported file back to the BEER version and date that
produced it. Figure metadata is kept format-safe so it never breaks an export.
"""
from __future__ import annotations

import datetime


def beer_version() -> str:
    try:
        import beer
        return getattr(beer, "__version__", "3")
    except Exception:
        return "3"


def figure_metadata(ext: str = "png") -> dict:
    """Format-appropriate matplotlib ``savefig(metadata=...)`` dict.

    PDF/SVG only accept specific keys, so we tailor the dict per format to avoid
    backend errors; PNG accepts arbitrary string keys.
    """
    soft = f"BEER v{beer_version()}"
    date = datetime.date.today().isoformat()
    e = (ext or "png").lower()
    if e == "pdf":
        return {"Creator": soft, "Producer": soft,
                "Subject": f"Generated by {soft} on {date}"}
    if e == "svg":
        return {"Creator": soft}
    # PNG and others: arbitrary string keys allowed.
    return {"Software": soft, "Creation Time": date,
            "Source": "https://github.com/chemgame/BEER"}


def text_header(comment: str = "# ", title: str | None = None) -> str:
    """Provenance comment block for text/CSV/script exports (trailing newline)."""
    soft = f"BEER v{beer_version()}"
    date = datetime.date.today().isoformat()
    lines = [f"{comment}Generated by {soft} on {date}",
             f"{comment}https://github.com/chemgame/BEER"]
    if title:
        lines.insert(0, f"{comment}{title}")
    return "\n".join(lines) + "\n"


def provenance_record() -> dict:
    """Provenance block for JSON exports."""
    return {"software": f"BEER v{beer_version()}",
            "generated": datetime.date.today().isoformat(),
            "url": "https://github.com/chemgame/BEER"}
