"""Interoperability exports: GFF3, B-factor PDB, PyMOL/ChimeraX scripts."""
from beer.io.track_export import (
    features_to_gff3, coloring_to_bfactor_pdb,
    coloring_to_pymol, coloring_to_chimerax, available_colour_tracks,
)

_DATA = {
    "seq": "MASTKLVWQRDEFGHIKLMNP",
    "disorder_scores": [0.1, 0.2, 0.8, 0.9, 0.7] + [0.1] * 16,
    "tm_bilstm_profile": [0.1] * 7 + [0.9, 0.95, 0.92] + [0.1] * 11,
}


def test_gff3_header_and_regions():
    gff = features_to_gff3(_DATA, "P12345")
    assert gff.startswith("##gff-version 3")
    assert "Generated by BEER v" in gff               # provenance stamp
    assert "disordered_region\t3\t5" in gff           # contiguous run >= 0.5
    assert "transmembrane_region\t8\t10" in gff


def test_available_tracks():
    tracks = dict(available_colour_tracks(_DATA))
    assert "disorder_scores" in tracks and "tm_bilstm_profile" in tracks
    assert "act_bilstm_profile" not in tracks          # not computed


def test_bfactor_pdb_rewrites_column():
    pdb = ("ATOM      1  CA  MET A   1       0.000   0.000   0.000  1.00  9.99           C\n"
           "ATOM      2  CA  ALA A   2       1.000   0.000   0.000  1.00  9.99           C")
    out = coloring_to_bfactor_pdb(pdb, [0.2, 0.5])
    assert out.startswith("REMARK")                    # provenance stamp
    atoms = [ln for ln in out.splitlines() if ln.startswith("ATOM")]
    assert atoms[0][60:66].strip() == "20.00"
    assert atoms[1][60:66].strip() == "50.00"
    assert coloring_to_bfactor_pdb(pdb, []) is None


def test_pymol_and_chimerax_scripts():
    pml = coloring_to_pymol(_DATA, "disorder_scores", "Disorder")
    assert "cmd.spectrum('b'" in pml and "beer_scores" in pml
    cxc = coloring_to_chimerax(_DATA, "disorder_scores", "Disorder")
    assert "color byattribute r:beerScore" in cxc
    assert coloring_to_pymol(_DATA, "act_bilstm_profile", "x") is None
